export const SET_BOOKS_DATA_IN_PROGRESS = 'SET_BOOKS_DATA_IN_PROGRESS';
export const SET_BOOKS_DATA_SUCCESS     = 'SET_BOOKS_DATA_SUCCESS';
export const SET_BOOKS_DATA_FAILED      = 'SET_BOOKS_DATA_FAILED';
export const CHANGE_BOOK_ITEM           = 'CHANGE_BOOK_ITEM';
export const DELETE_BOOK_ITEM           = 'DELETE_BOOK_ITEM';
